/*
 * Throwaway prototype for #19 phase 1: candidate visual styles.
 *
 * Every style is only a set of CSS custom properties. The gallery markup and
 * gallery.css are shared, so the comparison is fair and the chosen style can be
 * lifted into the app's real tokens later.
 */

export type Mode = "light" | "dark";

/** Colour and shadow tokens, which change between light and dark. */
export interface ModeTokens {
  bg: string;
  surface: string;
  "surface-2": string;
  text: string;
  muted: string;
  /** Decorative dividers. */
  border: string;
  /** Control boundaries (inputs, secondary buttons): needs 3:1 against surface. */
  "border-strong": string;
  link: string;
  primary: string;
  "on-primary": string;
  secondary: string;
  "on-secondary": string;
  "secondary-border": string;
  danger: string;
  "on-danger": string;
  /** Danger used as text on a surface (errors, outlined destructive). */
  "danger-text": string;
  focus: string;
  "empty-bg": string;
  "empty-fg": string;
  "empty-border": string;
  "discuss-bg": string;
  "discuss-fg": string;
  "discuss-border": string;
  "decided-bg": string;
  "decided-fg": string;
  "decided-border": string;
  up: string;
  "on-up": string;
  down: string;
  "on-down": string;
  "avatar-bg": string;
  "avatar-fg": string;
  "warning-bg": string;
  "warning-border": string;
  scrim: string;
  "shadow-card": string;
  "shadow-button": string;
  "shadow-dialog": string;
}

/** Type, shape and spacing tokens, shared by both modes. */
export interface CommonTokens {
  "font-heading": string;
  "font-body": string;
  "heading-weight": string;
  "heading-transform": string;
  "heading-tracking": string;
  "label-weight": string;
  "strong-weight": string;
  "text-sm": string;
  "text-base": string;
  "text-lg": string;
  "text-xl": string;
  "text-2xl": string;
  "line-height": string;
  "space-1": string;
  "space-2": string;
  "space-3": string;
  "space-4": string;
  "space-6": string;
  "radius-control": string;
  "radius-button": string;
  "radius-card": string;
  "radius-slot": string;
  "radius-dialog": string;
  "border-width": string;
  "control-border-width": string;
  "card-border-style": string;
  "card-border-width": string;
  "press-transform": string;
  "focus-width": string;
  "icon-stroke": string;
  transition: string;
}

export interface Rationale {
  mood: string;
  why: string[];
  tradeoffs: string[];
  /** ui-ux-pro-max entries this style was built from. */
  sources: string[];
}

export interface StyleDefinition {
  id: string;
  name: string;
  common: CommonTokens;
  light: ModeTokens;
  dark: ModeTokens;
  rationale: Rationale;
}

const baseType = {
  "text-sm": "0.875rem",
  "text-base": "1rem",
  "text-lg": "1.125rem",
  "text-xl": "1.375rem",
  "text-2xl": "1.75rem",
  "line-height": "1.5",
};

const spacing8 = {
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-6": "24px",
};

const noShadows = {
  "shadow-card": "none",
  "shadow-button": "none",
  "shadow-dialog": "0 12px 32px rgb(0 0 0 / 0.25)",
};

export const styles: StyleDefinition[] = [
  {
    id: "swiss-signal",
    name: "Swiss Signal",
    common: {
      "font-heading": '"Inter", system-ui, sans-serif',
      "font-body": '"Inter", system-ui, sans-serif',
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "-0.01em",
      "label-weight": "600",
      "strong-weight": "600",
      ...baseType,
      ...spacing8,
      "radius-control": "4px",
      "radius-button": "4px",
      "radius-card": "6px",
      "radius-slot": "4px",
      "radius-dialog": "8px",
      "border-width": "1px",
      "control-border-width": "1px",
      "card-border-style": "solid",
      "card-border-width": "1px",
      "press-transform": "none",
      "focus-width": "3px",
      "icon-stroke": "2",
      transition: "150ms ease-out",
    },
    light: {
      bg: "#F8FAFC",
      surface: "#FFFFFF",
      "surface-2": "#F1F5F9",
      text: "#0F172A",
      muted: "#475569",
      border: "#E2E8F0",
      "border-strong": "#64748B",
      link: "#1D4ED8",
      primary: "#2563EB",
      "on-primary": "#FFFFFF",
      secondary: "#FFFFFF",
      "on-secondary": "#0F172A",
      "secondary-border": "#64748B",
      danger: "#B91C1C",
      "on-danger": "#FFFFFF",
      "danger-text": "#B91C1C",
      focus: "#2563EB",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#475569",
      "empty-border": "#64748B",
      "discuss-bg": "#FEF3C7",
      "discuss-fg": "#78350F",
      "discuss-border": "#D97706",
      "decided-bg": "#047857",
      "decided-fg": "#FFFFFF",
      "decided-border": "#047857",
      up: "#047857",
      "on-up": "#FFFFFF",
      down: "#B91C1C",
      "on-down": "#FFFFFF",
      "avatar-bg": "#E2E8F0",
      "avatar-fg": "#0F172A",
      "warning-bg": "#FFFBEB",
      "warning-border": "#D97706",
      scrim: "rgb(15 23 42 / 0.55)",
      ...noShadows,
    },
    dark: {
      bg: "#0B1120",
      surface: "#111827",
      "surface-2": "#1E293B",
      text: "#F1F5F9",
      muted: "#A3B1C6",
      border: "#334155",
      "border-strong": "#7C8BA1",
      link: "#93C5FD",
      primary: "#60A5FA",
      "on-primary": "#0B1120",
      secondary: "#111827",
      "on-secondary": "#F1F5F9",
      "secondary-border": "#7C8BA1",
      danger: "#F87171",
      "on-danger": "#0B1120",
      "danger-text": "#FCA5A5",
      focus: "#93C5FD",
      "empty-bg": "#111827",
      "empty-fg": "#A3B1C6",
      "empty-border": "#7C8BA1",
      "discuss-bg": "#422006",
      "discuss-fg": "#FDE68A",
      "discuss-border": "#F59E0B",
      "decided-bg": "#34D399",
      "decided-fg": "#022C22",
      "decided-border": "#34D399",
      up: "#34D399",
      "on-up": "#022C22",
      down: "#F87171",
      "on-down": "#0B1120",
      "avatar-bg": "#334155",
      "avatar-fg": "#F1F5F9",
      "warning-bg": "#2A1F0A",
      "warning-border": "#F59E0B",
      scrim: "rgb(0 0 0 / 0.7)",
      ...noShadows,
    },
    rationale: {
      mood: "Quiet, exact, timetable-like. Information first, no decoration.",
      why: [
        "A grid of days and meals is a timetable; Swiss grid discipline makes it scan like one.",
        "Only colour on the page is meaning: blue for actions, amber for being discussed, green for decided.",
        "Inter is highly legible at small sizes and has tabular figures for dates and tallies.",
      ],
      tradeoffs: [
        "Least personality of the set; could feel like a work tool rather than a trip.",
        "Thin 1px borders lose some definition in direct sun compared with the heavier styles.",
      ],
      sources: [
        "style: Minimalism & Swiss Style (minimalism-and-swiss-style)",
        "color: Calendar & Scheduling App (calendar blue + event green)",
        "typography: Minimal Swiss (Inter / Inter)",
      ],
    },
  },
  {
    id: "street-brutal",
    name: "Street Brutal",
    common: {
      "font-heading": '"Lexend Mega", system-ui, sans-serif',
      "font-body": '"Public Sans", system-ui, sans-serif',
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "-0.04em",
      "label-weight": "700",
      "strong-weight": "700",
      ...baseType,
      ...spacing8,
      "radius-control": "6px",
      "radius-button": "6px",
      "radius-card": "8px",
      "radius-slot": "6px",
      "radius-dialog": "8px",
      "border-width": "3px",
      "control-border-width": "3px",
      "card-border-style": "solid",
      "card-border-width": "3px",
      "press-transform": "translate(3px, 3px)",
      "focus-width": "4px",
      "icon-stroke": "2.5",
      transition: "80ms linear",
    },
    light: {
      bg: "#FFF7ED",
      surface: "#FFFFFF",
      "surface-2": "#FFEDD5",
      text: "#000000",
      muted: "#3F3F46",
      border: "#000000",
      "border-strong": "#000000",
      link: "#9A3412",
      primary: "#F97316",
      "on-primary": "#000000",
      secondary: "#FFFFFF",
      "on-secondary": "#000000",
      "secondary-border": "#000000",
      danger: "#DC2626",
      "on-danger": "#FFFFFF",
      "danger-text": "#B91C1C",
      focus: "#2563EB",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#3F3F46",
      "empty-border": "#000000",
      "discuss-bg": "#FFDB58",
      "discuss-fg": "#000000",
      "discuss-border": "#000000",
      "decided-bg": "#4ECDC4",
      "decided-fg": "#000000",
      "decided-border": "#000000",
      up: "#4ECDC4",
      "on-up": "#000000",
      down: "#FF6B6B",
      "on-down": "#000000",
      "avatar-bg": "#FFDB58",
      "avatar-fg": "#000000",
      "warning-bg": "#FFEDD5",
      "warning-border": "#000000",
      scrim: "rgb(0 0 0 / 0.6)",
      "shadow-card": "4px 4px 0 #000000",
      "shadow-button": "3px 3px 0 #000000",
      "shadow-dialog": "8px 8px 0 #000000",
    },
    dark: {
      bg: "#121212",
      surface: "#1C1C1C",
      "surface-2": "#2A2A2A",
      text: "#FFFFFF",
      muted: "#D4D4D8",
      border: "#F5F5F5",
      "border-strong": "#F5F5F5",
      link: "#FDBA74",
      primary: "#FB923C",
      "on-primary": "#000000",
      secondary: "#1C1C1C",
      "on-secondary": "#FFFFFF",
      "secondary-border": "#F5F5F5",
      danger: "#FF6B6B",
      "on-danger": "#000000",
      "danger-text": "#FF8A8A",
      focus: "#93C5FD",
      "empty-bg": "#1C1C1C",
      "empty-fg": "#D4D4D8",
      "empty-border": "#F5F5F5",
      "discuss-bg": "#FFDB58",
      "discuss-fg": "#000000",
      "discuss-border": "#F5F5F5",
      "decided-bg": "#4ECDC4",
      "decided-fg": "#000000",
      "decided-border": "#F5F5F5",
      up: "#4ECDC4",
      "on-up": "#000000",
      down: "#FF6B6B",
      "on-down": "#000000",
      "avatar-bg": "#FFDB58",
      "avatar-fg": "#000000",
      "warning-bg": "#2A2A2A",
      "warning-border": "#FFDB58",
      scrim: "rgb(0 0 0 / 0.75)",
      "shadow-card": "4px 4px 0 #8A8A8A",
      "shadow-button": "3px 3px 0 #8A8A8A",
      "shadow-dialog": "8px 8px 0 #8A8A8A",
    },
    rationale: {
      mood: "Loud, playful, poster-on-a-lamp-post. Friends, not a booking engine.",
      why: [
        "3px black outlines and flat saturated blocks survive glare better than any soft shadow.",
        "Each meal state is its own block colour inside a hard outline, so gaps jump out.",
        "Hard offset shadows give an obvious pressed state for one-thumb tapping.",
      ],
      tradeoffs: [
        "Very opinionated; tiring if the maintainer wants the app to feel calm.",
        "Lexend Mega is wide: long trip names wrap early in headings at 360px.",
        "Dark mode is a compromise (grey hard shadows); the style is light-first.",
      ],
      sources: [
        "style: Neubrutalism (neubrutalism)",
        "color: Food Delivery / On-Demand (appetizing orange) + Neubrutalism accents #FFDB58 #FF6B6B #4ECDC4",
        "typography: Neubrutalist Bold (Lexend Mega / Public Sans)",
      ],
    },
  },
  {
    id: "soft-clay",
    name: "Soft Clay",
    common: {
      "font-heading": '"Varela Round", system-ui, sans-serif',
      "font-body": '"Nunito Sans", system-ui, sans-serif',
      "heading-weight": "400",
      "heading-transform": "none",
      "heading-tracking": "0",
      "label-weight": "700",
      "strong-weight": "700",
      ...baseType,
      ...spacing8,
      "radius-control": "14px",
      "radius-button": "16px",
      "radius-card": "22px",
      "radius-slot": "16px",
      "radius-dialog": "28px",
      "border-width": "2px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "2px",
      "press-transform": "scale(0.97)",
      "focus-width": "3px",
      "icon-stroke": "2.25",
      transition: "220ms cubic-bezier(0.34, 1.56, 0.64, 1)",
    },
    light: {
      bg: "#EAF7F4",
      surface: "#FFFFFF",
      "surface-2": "#F1FAF8",
      text: "#134E4A",
      muted: "#3D5F5B",
      border: "#CDE7E2",
      "border-strong": "#5B8C85",
      link: "#0F766E",
      primary: "#0F766E",
      "on-primary": "#FFFFFF",
      secondary: "#FFFFFF",
      "on-secondary": "#134E4A",
      "secondary-border": "#5B8C85",
      danger: "#B42318",
      "on-danger": "#FFFFFF",
      "danger-text": "#B42318",
      focus: "#EA580C",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#3D5F5B",
      "empty-border": "#5B8C85",
      "discuss-bg": "#FFE8D1",
      "discuss-fg": "#7C2D12",
      "discuss-border": "#F4A76A",
      "decided-bg": "#0F766E",
      "decided-fg": "#FFFFFF",
      "decided-border": "#0F766E",
      up: "#0F766E",
      "on-up": "#FFFFFF",
      down: "#B42318",
      "on-down": "#FFFFFF",
      "avatar-bg": "#FFE8D1",
      "avatar-fg": "#7C2D12",
      "warning-bg": "#FFF4E5",
      "warning-border": "#F4A76A",
      scrim: "rgb(19 78 74 / 0.45)",
      "shadow-card":
        "inset -3px -3px 6px rgb(19 78 74 / 0.06), 0 8px 20px -6px rgb(19 78 74 / 0.22)",
      "shadow-button":
        "inset -2px -3px 4px rgb(0 0 0 / 0.14), inset 2px 2px 4px rgb(255 255 255 / 0.35), 0 4px 10px -2px rgb(19 78 74 / 0.3)",
      "shadow-dialog": "0 24px 48px -12px rgb(19 78 74 / 0.4)",
    },
    dark: {
      bg: "#0C1A18",
      surface: "#15302C",
      "surface-2": "#1B3A36",
      text: "#E6FFFA",
      muted: "#A7C9C3",
      border: "#2A4B46",
      "border-strong": "#6A9C95",
      link: "#5EEAD4",
      primary: "#5EEAD4",
      "on-primary": "#042F2E",
      secondary: "#15302C",
      "on-secondary": "#E6FFFA",
      "secondary-border": "#6A9C95",
      danger: "#FCA5A5",
      "on-danger": "#450A0A",
      "danger-text": "#FCA5A5",
      focus: "#FDBA74",
      "empty-bg": "#15302C",
      "empty-fg": "#A7C9C3",
      "empty-border": "#6A9C95",
      "discuss-bg": "#4A2A12",
      "discuss-fg": "#FED7AA",
      "discuss-border": "#C2692B",
      "decided-bg": "#5EEAD4",
      "decided-fg": "#042F2E",
      "decided-border": "#5EEAD4",
      up: "#5EEAD4",
      "on-up": "#042F2E",
      down: "#FCA5A5",
      "on-down": "#450A0A",
      "avatar-bg": "#4A2A12",
      "avatar-fg": "#FED7AA",
      "warning-bg": "#2E2412",
      "warning-border": "#C2692B",
      scrim: "rgb(0 0 0 / 0.65)",
      "shadow-card": "inset -3px -3px 6px rgb(0 0 0 / 0.25), 0 10px 24px -8px rgb(0 0 0 / 0.6)",
      "shadow-button":
        "inset -2px -3px 4px rgb(0 0 0 / 0.25), inset 2px 2px 4px rgb(255 255 255 / 0.15), 0 4px 10px -2px rgb(0 0 0 / 0.5)",
      "shadow-dialog": "0 24px 48px -12px rgb(0 0 0 / 0.7)",
    },
    rationale: {
      mood: "Warm, soft and friendly, like a holiday app rather than a tool.",
      why: [
        "Pillowy, rounded shapes feel relaxed and approachable for a group of friends.",
        "Big radii and chunky buttons make tap targets obvious without looking heavy.",
        "Teal plus a warm apricot accent keeps food warmth without shouting.",
      ],
      tradeoffs: [
        "Soft shadows and pastels wash out in bright sun; state relies more on fill than outline.",
        "Most expensive style to render (layered inset shadows) and easiest to overdo.",
        "Varela Round ships one weight, so heading hierarchy comes from size only.",
      ],
      sources: [
        "style: Claymorphism (claymorphism)",
        "color: Productivity Tool (teal + orange accent), primary darkened to #0F766E for white text",
        "typography: Soft Rounded (Varela Round / Nunito Sans)",
      ],
    },
  },
  {
    id: "menu-card",
    name: "Menu Card",
    common: {
      "font-heading": '"Playfair Display SC", Georgia, serif',
      "font-body": '"Karla", system-ui, sans-serif',
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "0.01em",
      "label-weight": "700",
      "strong-weight": "700",
      ...baseType,
      ...spacing8,
      "radius-control": "2px",
      "radius-button": "2px",
      "radius-card": "0",
      "radius-slot": "2px",
      "radius-dialog": "2px",
      "border-width": "1px",
      "control-border-width": "1px",
      "card-border-style": "double",
      "card-border-width": "4px",
      "press-transform": "none",
      "focus-width": "3px",
      "icon-stroke": "1.75",
      transition: "0ms",
    },
    light: {
      bg: "#F7F2E8",
      surface: "#FFFDF8",
      "surface-2": "#F1E9DA",
      text: "#2B1810",
      muted: "#5C4A3D",
      border: "#D9CFC0",
      "border-strong": "#6B5A4A",
      link: "#8A1C1C",
      primary: "#2B1810",
      "on-primary": "#FFFDF8",
      secondary: "#FFFDF8",
      "on-secondary": "#2B1810",
      "secondary-border": "#6B5A4A",
      danger: "#B91C1C",
      "on-danger": "#FFFFFF",
      "danger-text": "#B91C1C",
      focus: "#A16207",
      "empty-bg": "#FFFDF8",
      "empty-fg": "#5C4A3D",
      "empty-border": "#8C7A68",
      "discuss-bg": "#F6E7C1",
      "discuss-fg": "#5A3A07",
      "discuss-border": "#A16207",
      "decided-bg": "#2B1810",
      "decided-fg": "#FFFDF8",
      "decided-border": "#2B1810",
      up: "#2F5D1F",
      "on-up": "#FFFFFF",
      down: "#8A1C1C",
      "on-down": "#FFFFFF",
      "avatar-bg": "#F1E9DA",
      "avatar-fg": "#2B1810",
      "warning-bg": "#FBF1DC",
      "warning-border": "#A16207",
      scrim: "rgb(43 24 16 / 0.55)",
      ...noShadows,
    },
    dark: {
      bg: "#15100C",
      surface: "#1F1812",
      "surface-2": "#2B221A",
      text: "#F3EBDD",
      muted: "#C9B9A3",
      border: "#4A3D30",
      "border-strong": "#9C8A73",
      link: "#F2A7A7",
      primary: "#F3EBDD",
      "on-primary": "#1A1410",
      secondary: "#1F1812",
      "on-secondary": "#F3EBDD",
      "secondary-border": "#9C8A73",
      danger: "#F87171",
      "on-danger": "#1A1410",
      "danger-text": "#F8A0A0",
      focus: "#E0B35A",
      "empty-bg": "#1F1812",
      "empty-fg": "#C9B9A3",
      "empty-border": "#8C7A68",
      "discuss-bg": "#3D2E12",
      "discuss-fg": "#F2D38B",
      "discuss-border": "#C99A3A",
      "decided-bg": "#F3EBDD",
      "decided-fg": "#1A1410",
      "decided-border": "#F3EBDD",
      up: "#A7D98C",
      "on-up": "#1A1410",
      down: "#F2A7A7",
      "on-down": "#1A1410",
      "avatar-bg": "#3A2E23",
      "avatar-fg": "#F3EBDD",
      "warning-bg": "#2B2212",
      "warning-border": "#C99A3A",
      scrim: "rgb(0 0 0 / 0.7)",
      ...noShadows,
    },
    rationale: {
      mood: "A printed restaurant menu: cream paper, ink, small caps, double rules.",
      why: [
        "The design-system search for this product returned the culinary pairing Playfair Display SC / Karla; this style leans into it.",
        "Paper-and-ink is matte and high contrast, which reads well outdoors.",
        "A decided meal becomes a solid ink line like a printed menu entry, so gaps are the blank lines.",
      ],
      tradeoffs: [
        "Serif small caps are decorative; kept to headings so restaurant names stay in Karla.",
        "Instant (0ms) state changes per the E-Ink entry feel abrupt next to the other styles.",
        "Charming, but a bit precious for a utility used standing in a queue.",
      ],
      sources: [
        "style: E-Ink / Paper (e-ink-paper) + Editorial Grid / Magazine (editorial-grid-magazine)",
        "color: Restaurant/Food Service (red + brown accent), primary moved to ink so red stays for destructive",
        "typography: design-system result for this product, Playfair Display SC / Karla",
      ],
    },
  },
  {
    id: "material-tonal",
    name: "Material Tonal",
    common: {
      "font-heading": '"Roboto", system-ui, sans-serif',
      "font-body": '"Roboto", system-ui, sans-serif',
      "heading-weight": "500",
      "heading-transform": "none",
      "heading-tracking": "0",
      "label-weight": "500",
      "strong-weight": "500",
      ...baseType,
      ...spacing8,
      "radius-control": "4px",
      "radius-button": "999px",
      "radius-card": "16px",
      "radius-slot": "12px",
      "radius-dialog": "28px",
      "border-width": "1px",
      "control-border-width": "1px",
      "card-border-style": "solid",
      "card-border-width": "0",
      "press-transform": "none",
      "focus-width": "3px",
      "icon-stroke": "2",
      transition: "200ms cubic-bezier(0.2, 0, 0, 1)",
    },
    light: {
      bg: "#F7F9FC",
      surface: "#FFFFFF",
      "surface-2": "#ECF1F7",
      text: "#191C1E",
      muted: "#41484D",
      border: "#DDE3EA",
      "border-strong": "#71787E",
      link: "#00629B",
      primary: "#00629B",
      "on-primary": "#FFFFFF",
      secondary: "#D1E4FF",
      "on-secondary": "#001D36",
      "secondary-border": "#71787E",
      danger: "#BA1A1A",
      "on-danger": "#FFFFFF",
      "danger-text": "#BA1A1A",
      focus: "#00629B",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#41484D",
      "empty-border": "#71787E",
      "discuss-bg": "#FFDDB8",
      "discuss-fg": "#2A1700",
      "discuss-border": "#FFDDB8",
      "decided-bg": "#A6F2CF",
      "decided-fg": "#002114",
      "decided-border": "#A6F2CF",
      up: "#006C4C",
      "on-up": "#FFFFFF",
      down: "#BA1A1A",
      "on-down": "#FFFFFF",
      "avatar-bg": "#D1E4FF",
      "avatar-fg": "#001D36",
      "warning-bg": "#FFF8F0",
      "warning-border": "#C97A00",
      scrim: "rgb(0 0 0 / 0.4)",
      "shadow-card": "0 1px 2px rgb(0 0 0 / 0.2), 0 1px 3px 1px rgb(0 0 0 / 0.1)",
      "shadow-button": "none",
      "shadow-dialog": "0 4px 8px 3px rgb(0 0 0 / 0.15), 0 1px 3px rgb(0 0 0 / 0.3)",
    },
    dark: {
      bg: "#111416",
      surface: "#1D2023",
      "surface-2": "#272A2D",
      text: "#E1E2E5",
      muted: "#C1C7CE",
      border: "#41484D",
      "border-strong": "#8B9198",
      link: "#97CBFF",
      primary: "#97CBFF",
      "on-primary": "#003353",
      secondary: "#38485C",
      "on-secondary": "#D1E4FF",
      "secondary-border": "#8B9198",
      danger: "#FFB4AB",
      "on-danger": "#690005",
      "danger-text": "#FFB4AB",
      focus: "#97CBFF",
      "empty-bg": "#1D2023",
      "empty-fg": "#C1C7CE",
      "empty-border": "#8B9198",
      "discuss-bg": "#653E00",
      "discuss-fg": "#FFDDB8",
      "discuss-border": "#653E00",
      "decided-bg": "#005138",
      "decided-fg": "#A6F2CF",
      "decided-border": "#005138",
      up: "#8AD6B3",
      "on-up": "#003826",
      down: "#FFB4AB",
      "on-down": "#690005",
      "avatar-bg": "#38485C",
      "avatar-fg": "#D1E4FF",
      "warning-bg": "#2B2215",
      "warning-border": "#E0A546",
      scrim: "rgb(0 0 0 / 0.6)",
      "shadow-card": "0 1px 3px rgb(0 0 0 / 0.5)",
      "shadow-button": "none",
      "shadow-dialog": "0 4px 12px rgb(0 0 0 / 0.6)",
    },
    rationale: {
      mood: "Familiar and platform-native, like a Google app on an Android phone.",
      why: [
        "The group already lives in Google Maps and Google Calendar; this looks like part of that family.",
        "Tonal containers (amber for discussing, green for decided) are a proven, accessible state system.",
        "Pill buttons and 28px dialogs are shapes people already know how to use one-handed.",
      ],
      tradeoffs: [
        "Least distinctive: the app will look generic, and a bit out of place on iPhones.",
        "Tonal fills are softer than outlines, so the empty versus decided contrast is gentler in sun.",
        "Faithful MD3 invites MD3 motion and ripples, which this prototype does not attempt.",
      ],
      sources: [
        "style: Material 3 Expressive (material-you-md3-mobile)",
        "color: Booking & Appointment App (sky blue + green), tuned to MD3 tone 40 for white text",
        "typography: Material You MD3 (Roboto System)",
      ],
    },
  },
  {
    id: "sunlight-max",
    name: "Sunlight Max",
    common: {
      "font-heading": '"Lexend", system-ui, sans-serif',
      "font-body": '"Atkinson Hyperlegible", system-ui, sans-serif',
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "-0.01em",
      "label-weight": "700",
      "strong-weight": "700",
      "text-sm": "1rem",
      "text-base": "1.125rem",
      "text-lg": "1.25rem",
      "text-xl": "1.5rem",
      "text-2xl": "1.875rem",
      "line-height": "1.45",
      ...spacing8,
      "radius-control": "8px",
      "radius-button": "8px",
      "radius-card": "10px",
      "radius-slot": "8px",
      "radius-dialog": "12px",
      "border-width": "2px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "2px",
      "press-transform": "none",
      "focus-width": "4px",
      "icon-stroke": "2.5",
      transition: "120ms ease-out",
    },
    light: {
      bg: "#FFFFFF",
      surface: "#FFFFFF",
      "surface-2": "#F4F4F5",
      text: "#000000",
      muted: "#27272A",
      border: "#0A0A0A",
      "border-strong": "#0A0A0A",
      link: "#1E40AF",
      primary: "#1E40AF",
      "on-primary": "#FFFFFF",
      secondary: "#FFFFFF",
      "on-secondary": "#000000",
      "secondary-border": "#0A0A0A",
      danger: "#9F1239",
      "on-danger": "#FFFFFF",
      "danger-text": "#9F1239",
      focus: "#1E40AF",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#27272A",
      "empty-border": "#0A0A0A",
      "discuss-bg": "#FDE047",
      "discuss-fg": "#000000",
      "discuss-border": "#0A0A0A",
      "decided-bg": "#000000",
      "decided-fg": "#FFFFFF",
      "decided-border": "#000000",
      up: "#14532D",
      "on-up": "#FFFFFF",
      down: "#9F1239",
      "on-down": "#FFFFFF",
      "avatar-bg": "#000000",
      "avatar-fg": "#FFFFFF",
      "warning-bg": "#FEF9C3",
      "warning-border": "#0A0A0A",
      scrim: "rgb(0 0 0 / 0.7)",
      ...noShadows,
    },
    dark: {
      bg: "#000000",
      surface: "#0A0A0A",
      "surface-2": "#1A1A1A",
      text: "#FFFFFF",
      muted: "#E4E4E7",
      border: "#FFFFFF",
      "border-strong": "#FFFFFF",
      link: "#BFDBFE",
      primary: "#BFDBFE",
      "on-primary": "#000000",
      secondary: "#0A0A0A",
      "on-secondary": "#FFFFFF",
      "secondary-border": "#FFFFFF",
      danger: "#FDA4AF",
      "on-danger": "#000000",
      "danger-text": "#FDA4AF",
      focus: "#FDE047",
      "empty-bg": "#0A0A0A",
      "empty-fg": "#E4E4E7",
      "empty-border": "#FFFFFF",
      "discuss-bg": "#FDE047",
      "discuss-fg": "#000000",
      "discuss-border": "#FDE047",
      "decided-bg": "#FFFFFF",
      "decided-fg": "#000000",
      "decided-border": "#FFFFFF",
      up: "#86EFAC",
      "on-up": "#000000",
      down: "#FDA4AF",
      "on-down": "#000000",
      "avatar-bg": "#FFFFFF",
      "avatar-fg": "#000000",
      "warning-bg": "#1A1A1A",
      "warning-border": "#FDE047",
      scrim: "rgb(0 0 0 / 0.8)",
      ...noShadows,
    },
    rationale: {
      mood: "Transit signage: black, white and one warning yellow. Built for glare.",
      why: [
        "Targets 7:1 text contrast (AAA) rather than 4.5:1, the Inclusive Design entry's bar.",
        "18px base text in Atkinson Hyperlegible, a face designed to keep letters distinct at a glance.",
        "Decided is solid black, being discussed is signal yellow, empty is a dashed outline: three shapes, not three tints.",
      ],
      tradeoffs: [
        "Austere; little warmth or food feeling.",
        "18px base means fewer meals per screen, so the grid scrolls further.",
        "Strong yellow reads as a warning, which may overstate a slot that is simply being discussed.",
      ],
      sources: [
        "style: Inclusive Design (inclusive-design)",
        "color: Coworking Space (amber + booking blue), pushed to 7:1",
        "typography: google-fonts Atkinson Hyperlegible, headings from Corporate Trust (Lexend)",
      ],
    },
  },
];

export function cssVariables(style: StyleDefinition, mode: Mode): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const [key, value] of Object.entries({ ...style.common, ...style[mode] })) {
    vars[`--${key}`] = value;
  }
  return vars;
}
