/*
 * Round 2 of the #19 style gallery: styles pushed in a travel direction, with
 * Menu Card (round 1) as the reference for "close". Motifs come only from
 * motif tokens (see MotifCommon in styles.ts): CSS gradients, masks and
 * pseudo-elements, no image files.
 */
import type { StyleDefinition } from "./styles.ts";

const type16 = {
  "text-sm": "0.875rem",
  "text-base": "1rem",
  "text-lg": "1.125rem",
  "text-xl": "1.375rem",
  "text-2xl": "1.75rem",
  "line-height": "1.5",
};

const spacing8 = {
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-6": "24px",
};

const flat = {
  "shadow-card": "0 0 transparent",
  "shadow-button": "none",
};

/** Full-bleed band across the top of a day card. */
const bleedBand = "calc(-1 * var(--space-4)) calc(-1 * var(--space-4)) 0";

/** Semicircle notches on both short edges: a ticket stub. */
const ticketMask =
  "radial-gradient(circle 7px at 0 50%, #0000 98%, #000) left / 51% 100% no-repeat, radial-gradient(circle 7px at 100% 50%, #0000 98%, #000) right / 51% 100% no-repeat";

/** Four triangles in the card corners, like photo-album corner mounts. */
const photoCorners =
  "linear-gradient(135deg, var(--corner) 14px, transparent 14px), linear-gradient(225deg, var(--corner) 14px, transparent 14px), linear-gradient(45deg, var(--corner) 14px, transparent 14px), linear-gradient(315deg, var(--corner) 14px, transparent 14px)";

export const roundTwo: StyleDefinition[] = [
  {
    id: "travel-journal",
    name: "Travel Journal",
    round: 2,
    common: {
      "font-heading": '"Quicksand", system-ui, sans-serif',
      "font-body": '"Quicksand", system-ui, sans-serif',
      "font-accent": '"Caveat", "Quicksand", cursive',
      "accent-scale": "1.4",
      "body-weight": "500",
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "0",
      "label-weight": "700",
      "strong-weight": "700",
      ...type16,
      ...spacing8,
      "radius-control": "10px 14px 12px 8px",
      "radius-button": "14px 18px 12px 16px",
      "radius-card": "18px 26px 20px 12px",
      "radius-slot": "12px 16px 10px 14px",
      "radius-dialog": "20px 28px 22px 16px",
      "border-width": "2px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "2px",
      "press-transform": "rotate(-1deg) scale(0.98)",
      "focus-width": "3px",
      "icon-stroke": "2.25",
      transition: "160ms ease-out",
      "page-texture": "radial-gradient(var(--texture-soft) 1.3px, transparent 1.8px)",
      "page-texture-size": "22px 22px",
      "card-texture": photoCorners,
      "card-texture-size": "auto",
      "texture-pct": "22%",
      "tape-display": "block",
      "decided-rotate": "-0.8deg",
    },
    light: {
      bg: "#FBF7EE",
      surface: "#FFFDF7",
      "surface-2": "#F3EDDF",
      text: "#2D2D2D",
      muted: "#55504A",
      border: "#D8CFBE",
      "border-strong": "#6E665B",
      link: "#2D5DA1",
      primary: "#2D5DA1",
      "on-primary": "#FFFFFF",
      secondary: "#FFFDF7",
      "on-secondary": "#2D2D2D",
      "secondary-border": "#6E665B",
      danger: "#B8322A",
      "on-danger": "#FFFFFF",
      "danger-text": "#B8322A",
      focus: "#2D5DA1",
      "empty-bg": "#FFFDF7",
      "empty-fg": "#55504A",
      "empty-border": "#6E665B",
      "discuss-bg": "#FFF3A6",
      "discuss-fg": "#3D3300",
      "discuss-border": "#C9A800",
      "decided-bg": "#2D5DA1",
      "decided-fg": "#FFFFFF",
      "decided-border": "#2D5DA1",
      up: "#2F6B3A",
      "on-up": "#FFFFFF",
      down: "#B8322A",
      "on-down": "#FFFFFF",
      "avatar-bg": "#FFF3A6",
      "avatar-fg": "#2D2D2D",
      "warning-bg": "#FFF6D6",
      "warning-border": "#C9A800",
      scrim: "rgb(45 45 45 / 0.5)",
      "shadow-card": "2px 3px 0 rgb(45 45 45 / 0.14)",
      "shadow-button": "1px 2px 0 rgb(45 45 45 / 0.25)",
      "shadow-dialog": "4px 6px 0 rgb(45 45 45 / 0.2)",
      "texture-ink": "#B8AE9C",
      "tape-bg": "repeating-linear-gradient(45deg, #F2B8B5 0 6px, #F7CFCC 6px 12px)",
      corner: "#D8CFBE",
    },
    dark: {
      bg: "#1E1B16",
      surface: "#26221C",
      "surface-2": "#312C24",
      text: "#F3EDE1",
      muted: "#C8BFB0",
      border: "#4A443A",
      "border-strong": "#8E857A",
      link: "#9CC0F5",
      primary: "#9CC0F5",
      "on-primary": "#14213A",
      secondary: "#26221C",
      "on-secondary": "#F3EDE1",
      "secondary-border": "#8E857A",
      danger: "#FF9A8F",
      "on-danger": "#2A0F0B",
      "danger-text": "#FFA59B",
      focus: "#F5D76E",
      "empty-bg": "#26221C",
      "empty-fg": "#C8BFB0",
      "empty-border": "#8E857A",
      "discuss-bg": "#4A4012",
      "discuss-fg": "#FFF1A8",
      "discuss-border": "#C9A800",
      "decided-bg": "#9CC0F5",
      "decided-fg": "#14213A",
      "decided-border": "#9CC0F5",
      up: "#9AD6A3",
      "on-up": "#10240F",
      down: "#FF9A8F",
      "on-down": "#2A0F0B",
      "avatar-bg": "#4A4012",
      "avatar-fg": "#FFF1A8",
      "warning-bg": "#2E2812",
      "warning-border": "#C9A800",
      scrim: "rgb(0 0 0 / 0.65)",
      "shadow-card": "2px 3px 0 rgb(0 0 0 / 0.4)",
      "shadow-button": "1px 2px 0 rgb(0 0 0 / 0.5)",
      "shadow-dialog": "4px 6px 0 rgb(0 0 0 / 0.5)",
      "texture-ink": "#5A5347",
      "tape-bg": "repeating-linear-gradient(45deg, #7A4A4A 0 6px, #8A5858 6px 12px)",
      corner: "#4A443A",
    },
    rationale: {
      mood: "A friend's trip notebook: dot-grid paper, washi tape, photo corners, pen notes.",
      sun: "Handwriting is the least legible face in glare, so Caveat is only used for large titles (day, section, page), never for restaurant names, slot states or buttons, which stay in Quicksand 500-700. The dot grid is 22% ink on the page only; slots have solid fills.",
      why: [
        "Feels like the trip itself rather than an app about it; closest in spirit to Menu Card's printed character.",
        "Decided meals are blue-ink slips, tilted slightly as if stuck in; discussing is a sticky-note yellow.",
        "Wobbly radii and tape make each day a page, which suits the day-by-day grid.",
      ],
      tradeoffs: [
        "Most decorative of the set; risks looking cute rather than trustworthy.",
        "Quicksand is geometric and light; body text needs weight 500 to hold up.",
        "The tilt on decided slots must stay under 1 degree or tap targets look misaligned.",
      ],
      sources: [
        "style: Sketch Hand-Drawn Mobile (sketch-hand-drawn-mobile) + E-Ink / Paper (e-ink-paper)",
        "color: sketch entry (pencil #2D2D2D, blue ink #2D5DA1, sticky #FFF9C4, red marker darkened)",
        "typography: Handwritten Charm (Caveat / Quicksand)",
      ],
    },
  },
  {
    id: "postcard-poster",
    name: "Postcard Poster",
    round: 2,
    common: {
      "font-heading": '"Barlow Condensed", system-ui, sans-serif',
      "font-body": '"Barlow", system-ui, sans-serif',
      "font-accent": '"Abril Fatface", Georgia, serif',
      "accent-scale": "1",
      "accent-weight": "400",
      "body-weight": "500",
      "heading-weight": "700",
      "heading-transform": "uppercase",
      "heading-tracking": "0.03em",
      "label-weight": "600",
      "strong-weight": "700",
      ...type16,
      "text-lg": "1.1875rem",
      ...spacing8,
      "radius-control": "3px",
      "radius-button": "3px",
      "radius-card": "4px",
      "radius-slot": "3px",
      "radius-dialog": "4px",
      "border-width": "2px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "2px",
      "press-transform": "translateY(1px)",
      "focus-width": "3px",
      "icon-stroke": "2.25",
      transition: "120ms ease-out",
      "page-texture":
        "repeating-conic-gradient(from 0deg at 50% -8%, var(--texture-soft) 0 5deg, transparent 5deg 12deg)",
      "texture-pct": "9%",
      "card-top-band": "6px",
      "day-title-padding": "var(--space-2) var(--space-4)",
      "day-title-margin": bleedBand,
      "day-title-radius": "2px 2px 0 0",
      "decided-outline-width": "2px",
    },
    light: {
      bg: "#F5E6C8",
      surface: "#FFF8EA",
      "surface-2": "#F3E3C3",
      text: "#1F2A30",
      muted: "#4A4A40",
      border: "#D9C59E",
      "border-strong": "#5E5A4C",
      link: "#1F4E79",
      primary: "#1F3A5F",
      "on-primary": "#FFF8EA",
      secondary: "#FFF8EA",
      "on-secondary": "#1F2A30",
      "secondary-border": "#5E5A4C",
      danger: "#9B1C1C",
      "on-danger": "#FFFFFF",
      "danger-text": "#9B1C1C",
      focus: "#1F3A5F",
      "empty-bg": "#FFF8EA",
      "empty-fg": "#4A4A40",
      "empty-border": "#5E5A4C",
      "discuss-bg": "#F2C879",
      "discuss-fg": "#2E1F00",
      "discuss-border": "#B07A1E",
      "decided-bg": "#1F6F6B",
      "decided-fg": "#FFF8EA",
      "decided-border": "#1F6F6B",
      up: "#1F6F6B",
      "on-up": "#FFF8EA",
      down: "#9B1C1C",
      "on-down": "#FFFFFF",
      "avatar-bg": "#F2C879",
      "avatar-fg": "#1F2A30",
      "warning-bg": "#FBEFD2",
      "warning-border": "#B07A1E",
      scrim: "rgb(31 42 48 / 0.55)",
      ...flat,
      "shadow-dialog": "0 10px 0 -4px rgb(31 42 48 / 0.25)",
      "texture-ink": "#C9843A",
      accent: "#B8440F",
      "on-accent": "#FFF8EA",
      "day-title-bg": "#B8440F",
      "day-title-fg": "#FFF8EA",
      "day-badge-fg": "var(--day-title-fg)",
    },
    dark: {
      bg: "#1B2328",
      surface: "#222C32",
      "surface-2": "#2C383F",
      text: "#F5E6C8",
      muted: "#D2C3A5",
      border: "#3E4B52",
      "border-strong": "#8C9BA3",
      link: "#F2B48A",
      primary: "#F5E6C8",
      "on-primary": "#1B2328",
      secondary: "#222C32",
      "on-secondary": "#F5E6C8",
      "secondary-border": "#8C9BA3",
      danger: "#FF8F80",
      "on-danger": "#2A0E0A",
      "danger-text": "#FF9D90",
      focus: "#F2C879",
      "empty-bg": "#222C32",
      "empty-fg": "#D2C3A5",
      "empty-border": "#8C9BA3",
      "discuss-bg": "#5A4418",
      "discuss-fg": "#F5D9A0",
      "discuss-border": "#C79A3A",
      "decided-bg": "#6FB7B3",
      "decided-fg": "#0F2524",
      "decided-border": "#6FB7B3",
      up: "#6FB7B3",
      "on-up": "#0F2524",
      down: "#FF8F80",
      "on-down": "#2A0E0A",
      "avatar-bg": "#5A4418",
      "avatar-fg": "#F5D9A0",
      "warning-bg": "#2E2A1C",
      "warning-border": "#C79A3A",
      scrim: "rgb(0 0 0 / 0.7)",
      ...flat,
      "shadow-dialog": "0 10px 0 -4px rgb(0 0 0 / 0.5)",
      "texture-ink": "#E0824F",
      accent: "#E0824F",
      "on-accent": "#1B2328",
      "day-title-bg": "#E0824F",
      "day-title-fg": "#1B2328",
      "day-badge-fg": "var(--day-title-fg)",
    },
    rationale: {
      mood: "A 1950s travel poster and the postcard you send from it: sunburst, flat colour bands, stamps.",
      sun: "Poster colour is flat and saturated, which survives glare, but sepia palettes drift low-contrast; every fill was pushed to at least 4.5:1 (cream on teal, dark ink on mustard). Abril Fatface is kept to big titles; everything you tap is Barlow. The sunburst is 9% on the page background only.",
      why: [
        "Each day card opens with a burnt-orange band, like the title strip on a poster; the day reads before the meals.",
        "Decided meals are teal stamps with a perforated inner edge, so they look collected, like postage.",
        "Condensed uppercase headings fit long Japanese place names in narrow columns.",
      ],
      tradeoffs: [
        "Strongly retro; the nostalgia may date quickly.",
        "Three strong hues (orange, teal, mustard) plus navy buttons is busy on a long grid.",
        "Uppercase condensed headings are harder to scan than mixed case at small sizes.",
      ],
      sources: [
        "style: Vintage Analog / Retro Film (vintage-analog-retro-film) + Flat Design (flat-design)",
        "color: Road Trip Planner (adventure orange + map teal) on the vintage entry's Faded Cream #F5E6C8",
        "typography: Retro Vintage (Abril Fatface, titles only) + Sports/Fitness (Barlow Condensed / Barlow)",
      ],
    },
  },
  {
    id: "boarding-pass",
    name: "Boarding Pass",
    round: 2,
    common: {
      "font-heading": '"IBM Plex Mono", ui-monospace, monospace',
      "font-body": '"IBM Plex Sans", system-ui, sans-serif',
      "font-accent": '"IBM Plex Mono", ui-monospace, monospace',
      "accent-scale": "1",
      "body-weight": "400",
      "heading-weight": "600",
      "heading-transform": "uppercase",
      "heading-tracking": "0.04em",
      "label-weight": "600",
      "strong-weight": "600",
      ...type16,
      ...spacing8,
      "radius-control": "6px",
      "radius-button": "6px",
      "radius-card": "14px",
      "radius-slot": "6px",
      "radius-dialog": "14px",
      "border-width": "1px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "1px",
      "press-transform": "none",
      "focus-width": "3px",
      "icon-stroke": "2",
      transition: "140ms ease-out",
      "day-badge-padding": "2px var(--space-2)",
      "day-badge-radius": "4px",
      "ticket-mask": ticketMask,
      "icon-divider-width": "2px",
      "icon-divider-gap": "10px",
      "route-display": "block",
      "route-pad": "22px",
      "route-dot-size": "12px",
    },
    light: {
      bg: "#EEF3FA",
      surface: "#FFFFFF",
      "surface-2": "#F1F5FB",
      text: "#0F1E3D",
      muted: "#46546B",
      border: "#D5DDEA",
      "border-strong": "#6B7A92",
      link: "#1E3A8A",
      primary: "#1E3A8A",
      "on-primary": "#FFFFFF",
      secondary: "#FFFFFF",
      "on-secondary": "#0F1E3D",
      "secondary-border": "#6B7A92",
      danger: "#B42318",
      "on-danger": "#FFFFFF",
      "danger-text": "#B42318",
      focus: "#C2410C",
      "empty-bg": "#FFFFFF",
      "empty-fg": "#46546B",
      "empty-border": "#6B7A92",
      "discuss-bg": "#FFE3CC",
      "discuss-fg": "#7A2E06",
      "discuss-border": "#EA580C",
      "decided-bg": "#1E3A8A",
      "decided-fg": "#FFFFFF",
      "decided-border": "#1E3A8A",
      up: "#166534",
      "on-up": "#FFFFFF",
      down: "#B42318",
      "on-down": "#FFFFFF",
      "avatar-bg": "#DCE6F7",
      "avatar-fg": "#0F1E3D",
      "warning-bg": "#FFF4EA",
      "warning-border": "#EA580C",
      scrim: "rgb(15 30 61 / 0.55)",
      ...flat,
      "shadow-card": "0 1px 2px rgb(15 30 61 / 0.12), 0 4px 12px -4px rgb(15 30 61 / 0.18)",
      "shadow-dialog": "0 16px 40px -8px rgb(15 30 61 / 0.35)",
      route: "#6B7A92",
      "day-badge-bg": "#EA580C",
      "day-badge-fg": "#000000",
    },
    dark: {
      bg: "#0B1426",
      surface: "#13203A",
      "surface-2": "#1B2A48",
      text: "#EAF0FA",
      muted: "#AEBBD0",
      border: "#2C3D5E",
      "border-strong": "#7D8DAA",
      link: "#A9C1F5",
      primary: "#A9C1F5",
      "on-primary": "#0B1426",
      secondary: "#13203A",
      "on-secondary": "#EAF0FA",
      "secondary-border": "#7D8DAA",
      danger: "#FF9B8F",
      "on-danger": "#2A0B07",
      "danger-text": "#FFA99E",
      focus: "#FB923C",
      "empty-bg": "#13203A",
      "empty-fg": "#AEBBD0",
      "empty-border": "#7D8DAA",
      "discuss-bg": "#4A2208",
      "discuss-fg": "#FFD2B0",
      "discuss-border": "#FB923C",
      "decided-bg": "#A9C1F5",
      "decided-fg": "#0B1426",
      "decided-border": "#A9C1F5",
      up: "#86D6A0",
      "on-up": "#062012",
      down: "#FF9B8F",
      "on-down": "#2A0B07",
      "avatar-bg": "#2C3D5E",
      "avatar-fg": "#EAF0FA",
      "warning-bg": "#2A1D12",
      "warning-border": "#FB923C",
      scrim: "rgb(0 0 0 / 0.7)",
      ...flat,
      "shadow-card": "0 4px 14px -4px rgb(0 0 0 / 0.6)",
      "shadow-dialog": "0 16px 40px -8px rgb(0 0 0 / 0.7)",
      route: "#7D8DAA",
      "day-badge-bg": "#FB923C",
      "day-badge-fg": "#000000",
    },
    rationale: {
      mood: "Boarding passes and rail tickets: gate codes, a dotted route, tear-off stubs.",
      sun: "Ticket design is naturally high-contrast (navy on white), so the tension is the mono face: uppercase mono is wide and slow to read, so it is only used for short labels (day titles, headings, badges), and restaurant names and notes stay in IBM Plex Sans. The route line and stubs are shape cues that need no colour to read.",
      why: [
        "Each day's meals hang off a dashed route line, like stops on a journey; decided stops are filled dots.",
        "A decided meal is a tear-off ticket stub (notched edges, perforated divider): you have your ticket for that meal.",
        "Orange gate-style day badges make 'Day 3' findable while scrolling.",
      ],
      tradeoffs: [
        "Leans on transport rather than food; the dining feel comes only from content.",
        "Route line and dots cost about 22px of width at 360px, so names wrap sooner.",
        "Notch masks clip the slot border, which Safari needs -webkit-mask for (included).",
      ],
      sources: [
        "style: Flat Design (flat-design), with ticket motifs built as CSS masks",
        "color: Airline (navy #1E3A8A + booking orange #EA580C)",
        "typography: Developer Mono (mono headings / IBM Plex Sans), via google-fonts IBM Plex Mono",
      ],
    },
  },
  {
    id: "cartographer",
    name: "Cartographer",
    round: 2,
    common: {
      "font-heading": '"Fraunces", Georgia, serif',
      "font-body": '"Cabin", system-ui, sans-serif',
      "font-accent": '"Fraunces", Georgia, serif',
      "accent-scale": "1",
      "body-weight": "400",
      "heading-weight": "600",
      "heading-transform": "none",
      "heading-tracking": "0",
      "label-weight": "600",
      "strong-weight": "600",
      ...type16,
      ...spacing8,
      "radius-control": "8px",
      "radius-button": "999px",
      "radius-card": "12px",
      "radius-slot": "10px",
      "radius-dialog": "16px",
      "border-width": "1px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "1px",
      "press-transform": "scale(0.98)",
      "focus-width": "3px",
      "icon-stroke": "2",
      transition: "180ms ease-out",
      "page-texture":
        "repeating-radial-gradient(circle at 18% 22%, transparent 0 26px, var(--texture-soft) 26px 27.5px), repeating-radial-gradient(circle at 88% 70%, transparent 0 34px, var(--texture-soft) 34px 35.5px)",
      "card-texture":
        "linear-gradient(var(--texture-soft) 1px, transparent 1px), linear-gradient(90deg, var(--texture-soft) 1px, transparent 1px)",
      "card-texture-size": "44px 44px",
      "texture-pct": "14%",
      "route-display": "block",
      "route-pad": "24px",
      "route-dot-size": "14px",
      "route-dot-radius": "50% 50% 50% 0",
      "route-dot-rotate": "-45deg",
    },
    light: {
      bg: "#F4EFE1",
      surface: "#FBF8EF",
      "surface-2": "#EDE6D2",
      text: "#1D3240",
      muted: "#4A5A5E",
      border: "#D6CDB4",
      "border-strong": "#6F7A70",
      link: "#0B5E7E",
      primary: "#0B5E7E",
      "on-primary": "#FFFFFF",
      secondary: "#FBF8EF",
      "on-secondary": "#1D3240",
      "secondary-border": "#6F7A70",
      danger: "#A8321E",
      "on-danger": "#FFFFFF",
      "danger-text": "#A8321E",
      focus: "#0B5E7E",
      "empty-bg": "#FBF8EF",
      "empty-fg": "#4A5A5E",
      "empty-border": "#6F7A70",
      "discuss-bg": "#F8D9B5",
      "discuss-fg": "#6A2C0A",
      "discuss-border": "#C9571F",
      "decided-bg": "#2F5D3A",
      "decided-fg": "#FFFFFF",
      "decided-border": "#2F5D3A",
      up: "#2F5D3A",
      "on-up": "#FFFFFF",
      down: "#A8321E",
      "on-down": "#FFFFFF",
      "avatar-bg": "#D5E8EE",
      "avatar-fg": "#1D3240",
      "warning-bg": "#FBEBD8",
      "warning-border": "#C9571F",
      scrim: "rgb(29 50 64 / 0.5)",
      ...flat,
      "shadow-card": "0 1px 0 rgb(29 50 64 / 0.08), 0 6px 16px -8px rgb(29 50 64 / 0.25)",
      "shadow-dialog": "0 18px 40px -10px rgb(29 50 64 / 0.4)",
      "texture-ink": "#8FA3A0",
      route: "#C9571F",
    },
    dark: {
      bg: "#0F1A1F",
      surface: "#16242B",
      "surface-2": "#1E2F37",
      text: "#E8E2D0",
      muted: "#B5B9AE",
      border: "#2E4148",
      "border-strong": "#7B8B86",
      link: "#7FD0EE",
      primary: "#7FD0EE",
      "on-primary": "#06222D",
      secondary: "#16242B",
      "on-secondary": "#E8E2D0",
      "secondary-border": "#7B8B86",
      danger: "#FF9C8A",
      "on-danger": "#2A0B05",
      "danger-text": "#FFA898",
      focus: "#F29A5E",
      "empty-bg": "#16242B",
      "empty-fg": "#B5B9AE",
      "empty-border": "#7B8B86",
      "discuss-bg": "#4A2A10",
      "discuss-fg": "#FFD5AE",
      "discuss-border": "#F29A5E",
      "decided-bg": "#8FCB9B",
      "decided-fg": "#0E2414",
      "decided-border": "#8FCB9B",
      up: "#8FCB9B",
      "on-up": "#0E2414",
      down: "#FF9C8A",
      "on-down": "#2A0B05",
      "avatar-bg": "#1E3A45",
      "avatar-fg": "#D5E8EE",
      "warning-bg": "#2A2014",
      "warning-border": "#F29A5E",
      scrim: "rgb(0 0 0 / 0.7)",
      ...flat,
      "shadow-card": "0 6px 16px -8px rgb(0 0 0 / 0.7)",
      "shadow-dialog": "0 18px 40px -10px rgb(0 0 0 / 0.8)",
      "texture-ink": "#4F6A70",
      route: "#F29A5E",
    },
    rationale: {
      mood: "An explorer's map: parchment, contour lines, a trail of pins across each day.",
      sun: "Map textures are busy by nature. Contours and the grid are held to 14% ink and never sit under slot text (slots are solid); the audit blends the texture into bg and surface and checks text against the result. Map colours (sea blue, park green, trail orange) were darkened well past their printed-map tints.",
      why: [
        "Each meal is a pin on the day's trail; decided pins are filled, open ones hollow.",
        "The grid's legend becomes a real map legend, which people already know how to read.",
        "Fraunces gives the soft, old-atlas label feel without the fussiness of small caps.",
      ],
      tradeoffs: [
        "Background texture is the most visible of the set and can feel noisy on a long page.",
        "Pin markers are decorative; without the slot fills they would be too small to carry state.",
        "Park green for decided and trail orange for the route are close to Christmas colours in dark mode.",
      ],
      sources: [
        "style: Organic Biophilic (organic-biophilic), earth-tone and texture guidance",
        "color: Travel/Tourism Agency (sky blue + adventure orange) + Road Trip Planner (map teal)",
        "typography: google-fonts Fraunces (variable, soft serif) with Cabin from Indie/Craft",
      ],
    },
  },
  {
    id: "washi-stationery",
    name: "Washi Stationery",
    round: 2,
    common: {
      "font-heading": '"Noto Serif JP", Georgia, serif',
      "font-body": '"Noto Sans JP", system-ui, sans-serif',
      "font-accent": '"Noto Serif JP", Georgia, serif',
      "accent-scale": "1",
      "body-weight": "400",
      "heading-weight": "600",
      "heading-transform": "none",
      "heading-tracking": "0.02em",
      "label-weight": "500",
      "strong-weight": "700",
      ...type16,
      "line-height": "1.6",
      ...spacing8,
      "radius-control": "4px",
      "radius-button": "4px",
      "radius-card": "6px",
      "radius-slot": "4px",
      "radius-dialog": "6px",
      "border-width": "1px",
      "control-border-width": "1px",
      "card-border-style": "solid",
      "card-border-width": "1px",
      "press-transform": "none",
      "focus-width": "3px",
      "icon-stroke": "1.75",
      transition: "200ms ease-out",
      "page-texture":
        "radial-gradient(circle at 50% 100%, transparent 0 9px, var(--texture-soft) 9px 10.5px, transparent 10.5px 15px, var(--texture-soft) 15px 16.5px, transparent 16.5px), radial-gradient(circle at 50% 100%, transparent 0 9px, var(--texture-soft) 9px 10.5px, transparent 10.5px 15px, var(--texture-soft) 15px 16.5px, transparent 16.5px)",
      "page-texture-size": "34px 17px",
      "page-texture-position": "0 0, 17px 8.5px",
      "texture-pct": "10%",
      "card-top-band": "3px",
      "stamp-ring-width": "2px",
      "stamp-radius": "50%",
      "stamp-rotate": "-10deg",
    },
    light: {
      bg: "#F3EEE3",
      surface: "#FBF8F1",
      "surface-2": "#ECE5D6",
      text: "#1F2A38",
      muted: "#4F5563",
      border: "#D9D0BE",
      "border-strong": "#707585",
      link: "#2B4C7E",
      primary: "#2B4C7E",
      "on-primary": "#FFFFFF",
      secondary: "#FBF8F1",
      "on-secondary": "#1F2A38",
      "secondary-border": "#707585",
      danger: "#8E1F2A",
      "on-danger": "#FFFFFF",
      "danger-text": "#8E1F2A",
      focus: "#2B4C7E",
      "empty-bg": "#FBF8F1",
      "empty-fg": "#4F5563",
      "empty-border": "#707585",
      "discuss-bg": "#EFE0B9",
      "discuss-fg": "#4A3A10",
      "discuss-border": "#B39447",
      "decided-bg": "#2B4C7E",
      "decided-fg": "#FBF8F1",
      "decided-border": "#2B4C7E",
      up: "#3B6B45",
      "on-up": "#FFFFFF",
      down: "#8E1F2A",
      "on-down": "#FFFFFF",
      "avatar-bg": "#E3E8F0",
      "avatar-fg": "#1F2A38",
      "warning-bg": "#F7EDD3",
      "warning-border": "#B39447",
      scrim: "rgb(31 42 56 / 0.5)",
      ...flat,
      "shadow-card": "0 1px 3px rgb(31 42 56 / 0.08)",
      "shadow-dialog": "0 14px 32px -10px rgb(31 42 56 / 0.35)",
      "texture-ink": "#7D8FA8",
      accent: "#C5413A",
      "on-accent": "#FFFFFF",
      stamp: "#F4A49A",
      "decided-icon": "#F4A49A",
    },
    dark: {
      bg: "#141A22",
      surface: "#1B232E",
      "surface-2": "#242E3B",
      text: "#EDE7DA",
      muted: "#B9B4A8",
      border: "#333E4D",
      "border-strong": "#7D8594",
      link: "#9DB7E0",
      primary: "#9DB7E0",
      "on-primary": "#10182A",
      secondary: "#1B232E",
      "on-secondary": "#EDE7DA",
      "secondary-border": "#7D8594",
      danger: "#F4978E",
      "on-danger": "#2A0B0B",
      "danger-text": "#F6A39B",
      focus: "#E8C77A",
      "empty-bg": "#1B232E",
      "empty-fg": "#B9B4A8",
      "empty-border": "#7D8594",
      "discuss-bg": "#4A3F1C",
      "discuss-fg": "#F3E2B0",
      "discuss-border": "#B39447",
      "decided-bg": "#9DB7E0",
      "decided-fg": "#10182A",
      "decided-border": "#9DB7E0",
      up: "#9CCBA5",
      "on-up": "#0F2414",
      down: "#F4978E",
      "on-down": "#2A0B0B",
      "avatar-bg": "#2B3A52",
      "avatar-fg": "#E3E8F0",
      "warning-bg": "#2A2415",
      "warning-border": "#B39447",
      scrim: "rgb(0 0 0 / 0.7)",
      ...flat,
      "shadow-card": "0 2px 6px rgb(0 0 0 / 0.4)",
      "shadow-dialog": "0 14px 32px -10px rgb(0 0 0 / 0.7)",
      "texture-ink": "#55657D",
      accent: "#E0645A",
      "on-accent": "#10182A",
      stamp: "#9E1B1B",
      "decided-icon": "#9E1B1B",
    },
    rationale: {
      mood: "Japanese stationery and an ekiben wrapper: washi paper, indigo and vermilion, a seigaiha wave, a hanko seal.",
      sun: "Muted, soft tones are the risk here: the washi palette's greys and pale indigo were pushed to AA against paper, and the pale ochre for 'being discussed' carries dark text. The hanko seal is a ring around the check icon, so the stamp adds character without replacing the icon or text. The wave is 10% ink on the page only.",
      why: [
        "Fits a Tokyo trip directly; the hanko ring on decided meals reads as 'approved', which is what deciding is.",
        "Indigo (ai) for decided and actions, vermilion (shu) only for the seal and card edge, the way Japanese print uses them.",
        "Calmest of the round 2 styles; closest to Menu Card's restraint.",
      ],
      tradeoffs: [
        "Culturally specific: lovely for Japan, odd for a trip to Lisbon.",
        "The seal ring is small; state is really carried by the indigo fill, the seal is flavour.",
        "Noto Serif JP headings are heavy downloads if Japanese glyphs are ever needed (Latin subset only here).",
      ],
      sources: [
        "typography: Japanese Elegant (Noto Serif JP / Noto Sans JP)",
        "style: E-Ink / Paper (e-ink-paper) for the paper feel + Organic Biophilic (organic-biophilic) muted naturals",
        "color: Hotel/Hospitality (navy + accent) retuned to ai indigo #2B4C7E and shu vermilion",
      ],
    },
  },
  {
    id: "field-guide",
    name: "Field Guide",
    round: 2,
    common: {
      "font-heading": '"Zilla Slab", Georgia, serif',
      "font-body": '"Source Sans 3", system-ui, sans-serif',
      "font-accent": '"Zilla Slab", Georgia, serif',
      "accent-scale": "1",
      "body-weight": "400",
      "heading-weight": "700",
      "heading-transform": "none",
      "heading-tracking": "0",
      "label-weight": "600",
      "strong-weight": "700",
      ...type16,
      ...spacing8,
      "radius-control": "4px",
      "radius-button": "4px",
      "radius-card": "2px 10px 10px 2px",
      "radius-slot": "4px",
      "radius-dialog": "4px",
      "border-width": "1px",
      "control-border-width": "2px",
      "card-border-style": "solid",
      "card-border-width": "1px",
      "press-transform": "translateY(1px)",
      "focus-width": "3px",
      "icon-stroke": "2",
      transition: "120ms ease-out",
      "page-texture":
        "repeating-linear-gradient(0deg, var(--texture-soft) 0 1px, transparent 1px 28px)",
      "texture-pct": "16%",
      "card-spine": "6px",
      "day-title-padding": "var(--space-2) var(--space-3)",
      "day-title-margin": "calc(-1 * var(--space-4)) 0 0 calc(-1 * var(--space-4) + 6px)",
      "day-title-radius": "0 0 6px 0",
      "day-title-align": "flex-start",
      "day-badge-padding": "0 var(--space-2)",
      "day-badge-radius": "999px",
      "entry-number-display": "inline-flex",
    },
    light: {
      bg: "#EDE9DA",
      surface: "#FAF8F0",
      "surface-2": "#E9E4D1",
      text: "#22281C",
      muted: "#4C5242",
      border: "#CFC8AE",
      "border-strong": "#6B6E58",
      link: "#3E5A1E",
      primary: "#3E5A1E",
      "on-primary": "#FFFFFF",
      secondary: "#FAF8F0",
      "on-secondary": "#22281C",
      "secondary-border": "#6B6E58",
      danger: "#A23B1C",
      "on-danger": "#FFFFFF",
      "danger-text": "#A23B1C",
      focus: "#A23B1C",
      "empty-bg": "#FAF8F0",
      "empty-fg": "#4C5242",
      "empty-border": "#6B6E58",
      "discuss-bg": "#F7E3A1",
      "discuss-fg": "#3A2C00",
      "discuss-border": "#C99A1E",
      "decided-bg": "#6B4A1F",
      "decided-fg": "#FFFFFF",
      "decided-border": "#6B4A1F",
      up: "#3E5A1E",
      "on-up": "#FFFFFF",
      down: "#A23B1C",
      "on-down": "#FFFFFF",
      "avatar-bg": "#E3E8CF",
      "avatar-fg": "#22281C",
      "warning-bg": "#FAEFC9",
      "warning-border": "#C99A1E",
      scrim: "rgb(34 40 28 / 0.55)",
      ...flat,
      "shadow-card": "0 1px 2px rgb(34 40 28 / 0.15)",
      "shadow-dialog": "0 12px 28px -8px rgb(34 40 28 / 0.4)",
      "texture-ink": "#8C9A74",
      accent: "#F2B233",
      "on-accent": "#22281C",
      "day-title-bg": "#3E5A1E",
      "day-title-fg": "#FAF8F0",
      "day-badge-bg": "#F2B233",
      "day-badge-fg": "#22281C",
    },
    dark: {
      bg: "#16190F",
      surface: "#1E2216",
      "surface-2": "#282D1E",
      text: "#EEEAD8",
      muted: "#BDBAA6",
      border: "#3A3F2C",
      "border-strong": "#858A70",
      link: "#B7D38A",
      primary: "#B7D38A",
      "on-primary": "#16190F",
      secondary: "#1E2216",
      "on-secondary": "#EEEAD8",
      "secondary-border": "#858A70",
      danger: "#FF9F85",
      "on-danger": "#2A0E05",
      "danger-text": "#FFAB94",
      focus: "#F2B233",
      "empty-bg": "#1E2216",
      "empty-fg": "#BDBAA6",
      "empty-border": "#858A70",
      "discuss-bg": "#4A3D10",
      "discuss-fg": "#F7E3A1",
      "discuss-border": "#C99A1E",
      "decided-bg": "#E0B877",
      "decided-fg": "#1E1508",
      "decided-border": "#E0B877",
      up: "#B7D38A",
      "on-up": "#16190F",
      down: "#FF9F85",
      "on-down": "#2A0E05",
      "avatar-bg": "#343B25",
      "avatar-fg": "#E3E8CF",
      "warning-bg": "#2A2510",
      "warning-border": "#C99A1E",
      scrim: "rgb(0 0 0 / 0.7)",
      ...flat,
      "shadow-card": "0 2px 6px rgb(0 0 0 / 0.5)",
      "shadow-dialog": "0 12px 28px -8px rgb(0 0 0 / 0.7)",
      "texture-ink": "#4A5236",
      accent: "#F2B233",
      "on-accent": "#16190F",
      "day-title-bg": "#B7D38A",
      "day-title-fg": "#16190F",
      "day-badge-bg": "#F2B233",
      "day-badge-fg": "#16190F",
    },
    rationale: {
      mood: "A cloth-bound field guide: olive covers, index tabs, numbered entries, ruled pages.",
      sun: "Guidebooks are already built to be read outdoors, so this is the easiest compromise: the travel feel is structural (tabs, numbers, spine) rather than textural, and the only texture is 16% ruled lines on the page background. Slab headings keep their weight in glare better than a high-contrast serif like Menu Card's.",
      why: [
        "Each day is an index tab on the card's corner, so scrolling the grid feels like flipping chapters.",
        "Proposals are numbered entries (1, 2, 3), which makes 'let's go with 2' easy to say out loud.",
        "Closest cousin of Menu Card: printed matter, warm paper, but more robust and less precious.",
      ],
      tradeoffs: [
        "Outdoorsy olive-and-khaki may read as hiking rather than eating.",
        "Brown for decided is less celebratory than a green or blue.",
        "Tabs rely on a negative margin trick that must be re-done properly in the real components.",
      ],
      sources: [
        "style: Organic Biophilic (organic-biophilic) earth palette + Editorial Grid / Magazine (editorial-grid-magazine) numbering",
        "color: Organic Biophilic (forest green, earth brown) with a safety-yellow accent",
        "typography: google-fonts Zilla Slab headings + Source Sans 3 body (from Corporate Trust)",
      ],
    },
  },
];
